# Dockerfile.admin
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY .env ./
COPY admin/ ./admin
COPY database/ ./database
COPY config.py logger.py ./

CMD ["flask", "--app", "admin.app", "run", "--host", "0.0.0.0", "--port", "5000"]