version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: telegram_bot
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - api
      - migrate
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    depends_on:
      - migrate
    restart: unless-stopped

  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    container_name: admin
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=production
    depends_on:
      - api
      - migrate
    restart: unless-stopped

#  migrate:
#    build:
#      context: .
#      dockerfile: Dockerfile.migrate
#    container_name: migrate
#    volumes:
#      - ./db.sqlite3:/app/db.sqlite3
#      - ./migrations:/app/migrations
#    environment:
#      - PYTHONPATH=/app
#    restart: on-failure

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - admin
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

volumes:
  db_data:
  logs: