# Dockerfile.admin
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY .env ./
COPY admin/ ./admin
COPY database/ ./database
COPY config.py logger.py ./

ENV PYTHONUNBUFFERED=1
ENV DOCKER_ENV=1

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "admin.app:app"]