FROM python:3.10-slim

WORKDIR /app

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем только нужные файлы для бота
COPY main.py .
COPY handlers/ ./handlers/
COPY database/ ./database/
COPY buns_data.py .
COPY logger.py .
COPY migrations/ ./migrations/

# Создаем директорию для логов
RUN mkdir -p logs

# Команда запуска
CMD ["python", "main.py"]