FROM nginx:alpine

RUN apk add --no-cache openssl

COPY nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /etc/nginx/certs && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/certs/server.key \
    -out /etc/nginx/certs/server.crt \
    -subj "/C=RU/ST=State/L=City/O=Organization/OU=Unit/CN=37.252.22.232" && \
    chmod 600 /etc/nginx/certs/server.key /etc/nginx/certs/server.crt