FROM python:3.10-slim

WORKDIR /app

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем только нужные файлы для миграций
COPY alembic.ini ./
COPY database/ ./database/
COPY migrations/ ./migrations/

# Команда для выполнения миграций
CMD ["alembic", "upgrade", "head"]