FROM python:3.11-slim

WORKDIR /app
COPY admin/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY admin/app.py .
COPY admin/templates ./templates
COPY admin/static ./static

RUN pip install gunicorn

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "2", "app:app"]