FROM python:3.10-slim

WORKDIR /app

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем только нужные файлы для админ-панели
COPY admin/ ./admin/
COPY database/ ./database/
COPY logger.py .
COPY migrations/ ./migrations/

# Создаем директорию для логов
RUN mkdir -p logs

# Команда запуска Flask
CMD ["python", "admin/app.py"]