FROM python:3.10-slim

WORKDIR /app

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем только нужные файлы для API
COPY config.py .
COPY api/ ./api/
COPY database/ ./database/
COPY logger.py .

# Создаем директорию для логов
RUN mkdir -p logs

# Команда запуска FastAPI с Uvicorn
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]